### ISSUE TITLE
FF4 data

### ISSUE THREAD

**Issue by ghost** [marco-calautti/FF4Tools#2]
Hi @marco-calautti .
Sorry for opening an issue for this regard, I didn't see any email to contact you otherwise about it.
Are you open to working with ff4 again as I would like to explore the other file formats and stat/magic data?

**Comment by marco-calautti** [comment]
Hi, unfortunately i do not have much time left nowadays. But I can suggest asking at romhacking.net. that's a big romhacking community.

**Comment by marco-calautti** [comment]
I also remember this guy was working on an editor for changing stats and other data: https://gamefaqs.gamespot.com/boards/615911-final-fantasy-iv-the-complete-collection/72692214

**Comment by ghost** [comment]
> Hi, unfortunately i do not have much time left nowadays. But I can suggest asking at romhacking.net. that's a big romhacking community.

Do they do paid jobs at romhacking.net? I wouldn't mind that with help cracking fully all the data and do more pay-compensated tasks with the game makeup and data.

> I also remember this guy was working on an editor for changing stats and other data: https://gamefaqs.gamespot.com/boards/615911-final-fantasy-iv-the-complete-collection/72692214

I remember Natreg and FF4CC Editor, but I believe he's stopped working on it for a while since could only edit data on monsters, while only viewing the other data (characters, maps, stats, spells, items, dialog). I'm quite certain he rarely visits gamefaqs as often and with no other contact to him.
