### ISSUE TITLE
repacked pac.bin causes FMV soft-lock

### ISSUE THREAD

**Issue by ghost** [marco-calautti/FF4Tools#4]
There are lingering issues when repacking the pac.bin causing the game to soft-lock when FMV plays. It occurs, when going to the Tower of Zot for the first time (airship FMV)
Flying to the Lunar Surface from the Blue Planet for the first time (tested with save).
This happens with vanilla game, no audio file replacements.

**Comment by marco-calautti** [comment]
Can you tell me which files you replaced and the command you used?

Il sab 26 mar 2022, 04:38 ornitier199 ***@***.***> ha scritto:

**Comment by ghost** [comment]
I used the following commands and replaced:
```
FF4Archiver -import PAC0.BIN PAC1.BIN /data/FPC.lzs=C:\_pac\data\FPC.lzs
FF4Archiver -import PAC0.BIN PAC1.BIN /data/btl_char00.lzs=C:\_pac\data\btl_char00.lzs
FF4Archiver -import PAC0.BIN PAC1.BIN /data/battle/BattleFF4Char.lzs=C:\_pac\data\battle\BattleFF4Char.lzs
```

**Comment by marco-calautti** [comment]
Ok, are those files in any way related to those scenes?

Il sab 26 mar 2022, 12:20 ornitier199 ***@***.***> ha scritto:

**Comment by ghost** [comment]
> 

Yes, the FPC, fpc are the field sprites. It only happens with a few FMVs. It didn't soft lock with the Leviathan FMV, but did when going to the Tower of Zot.
Testing form a further save, it happens again when traveling to the Blue Planet to the Lunar Moon FMV.
I can replace only one file and this all happens again.
I tested again from a complete new game and still the same results as mentioned above.
Furthermore, it happens whether you load the game from iso or directory. it's the same in all cases. PAC gets modified FMV in those situations will get soft locked.

**Comment by marco-calautti** [comment]
What makes you believe is the packer at fault, and bit your modified files?

We should first distinguish the two cases.


Il sab 26 mar 2022, 14:28 ornitier199 ***@***.***> ha scritto:

**Comment by marco-calautti** [comment]
If I recall well, FMVs are located on a dedicated area of the pac. So, there should not be any correlation on disk between your lzs files and the corresponding fmv. I fear this has more to do on how you modified the lzs file.

**Comment by ghost** [comment]
> If I recall well, FMVs are located on a dedicated area of the pac. So, there should not be any correlation on disk between your lzs files and the corresponding fmv. I fear this has more to do on how you modified the lzs file.

There's only one way to repack an lzs with the tool. There's only one way definitively to edit a tm2 inside an lzs archive.
There's only one way to repack the pac.bin.
FMVs are located outside the pac.bin, neither of which have been touched in anyway; and in regards to this dedicated area of FMV on the pac, if such, there's no way to even mess with that as this tool doesn't touch such a dedicated area of the pac.bin, right?

**Comment by ghost** [comment]
I don't what is the problem only that occurs whenever I repack the pac.bin. There's isn't a way to debug anything to find when it or what causes it.

**Comment by marco-calautti** [comment]
The fact that FMVs are even outside of the pac suggests even more they the archive is probably not the cause. How did you modify the tm2. Did you increase its resolution, or something like that?

**Comment by marco-calautti** [comment]
As an additional check. Can ou try to import *all* the files you need in one shot, instead if running the command multiple times on the same archive?
With the packer you  can import whole directories

**Comment by marco-calautti** [comment]
The other thing you could try is to extract the pac with Vash's tool and repack it with it. If you still get the problem also with his packer, then it is definitely something wrong with your files.

This is the unpacker which extracts all files: https://romhacking.it/upload/tools/[84]FF4_unpac.rar

This is the packer that recreates the whole pac from scratch (you cannot import only specific files like my tool): https://romhacking.it/upload/tools/[83]FF4_pac.rar

**Comment by ghost** [comment]
> The fact that FMVs are even outside of the pac suggests even more they the archive is probably not the cause. How did you modify the tm2. Did you increase its resolution, or something like that?

No I did not because I cannot in anyway without crashing the game.

Maybe the emulation?

> As an additional check. Can ou try to import _all_ the files you need in one shot, instead if running the command multiple times on the same archive? With the packer you can import whole directories

Yes I tried that. Yielded the same result.



> The other thing you could try is to extract the pac with Vash's tool and repack it with it. If you still get the problem also with his packer, then it is definitely something wrong with your files.
> 
> This is the unpacker which extracts all files: [https://romhacking.it/upload/tools/[84]FF4_unpac.rar](https://romhacking.it/upload/tools/%5B84%5DFF4_unpac.rar)
> 
> This is the packer that recreates the whole pac from scratch (you cannot import only specific files like my tool): [https://romhacking.it/upload/tools/[83]FF4_pac.rar](https://romhacking.it/upload/tools/%5B83%5DFF4_pac.rar)

What are the commands for this CLI? It has no readme.
I'm having a look at some other things, but eventually we'll figure it out.

**Comment by marco-calautti** [comment]
If I recall well, you simply put the exes in the same directory of the PACs and run the exe you need without additional parameters

**Comment by ghost** [comment]
> If I recall well, you simply put the exes in the same directory of the PACs and run the exe you need without additional parameters

If use Vash's tool replacing only one file `BattleFF4Char.lzs` on a completely, fresh, original unedited pac.bin, the game will not load at all.
Your tool doesn't do that.
Seems to be ways of handling the two. Would it be possible to edit eboot to make the game read the files outside the pac.bin and get the file sizes from the file itself? Since the emulator can already read the game outside of the iso?
That way any tribulations like this would be avoided?

**Comment by marco-calautti** [comment]
You must check if Vash's tool automatically decompresses the lzs like my tool or not. If it doesn't you should take care of this with my decompressor.

**Comment by marco-calautti** [comment]
Anyway, if you are getting so many issues with both tools, i fear your tribulations are not depending on the repacking. Such tools have both been used to replace a lot of files for a fan translation, including modified tm2 files and the message_en.lzs among other things, and we had not a single issue.

**Comment by marco-calautti** [comment]
Without knowing how you modified that lzs file there is not much I can do in troubleshooting the issue.

**Comment by ghost** [comment]
> You must check if Vash's tool automatically decompresses the lzs like my tool or not. If it doesn't you should take care of this with my decompressor.

That would explain why the game didn't load.
I don't know, is this the first time any has touched FPC.lzs? My last guess would be bgm_zot.at3.
To be honest only the at3 has been giving me issues like these when ever thing is narrowed down.

I figured how to get the correct bitrate this time and my at3 where much much smaller this time and all worked as they should (even fixed the bgm_airship.at3).

at3 may be the most delicate in this case with the game.

**Comment by ghost** [comment]
`bgm_somewhere.at3` actually, since that bgm triggers first, than the airship scene, the FMV then the mapjump to tower of zot.
The audio is the issue not the lzs or any of edited lzs, (just finished testing—the at3 caused the softlock) Probably to update the event there to compensate the new at3 so that the FMV doesn't soft-lock on load/preload.
The at3 plays fine in game, its just when the event readies an FMV in some cases it'll soft-lock other FMVs play okay.
Other than the FMV everything else works fine.

**Comment by marco-calautti** [comment]
Ok, so it seems one has to be careful on how the at3 are encoded/replaced. So, i guess we can safely conclude that my packer has no obvious bugs.

**Comment by ghost** [comment]
> Ok, so it seems one has to be careful on how the at3 are encoded/replaced. So, i guess we can safely conclude that my packer has no obvious bugs.

Yep. Closing issue.
