### ISSUE TITLE
pac.bin not fully extracting

### ISSUE THREAD

**Issue by ghost** [marco-calautti/FF4Tools#5]
There appears to be a file not extracted from pac.bin `boot.lzs`. I see there are three main directories:
`data\`
`sound\`
`program\`

data and sound extract, but not program\ directory, with boot.lzs
I've been working on eboot modification and so far game can read data outside of pac, but with exception, it missing boot.lzs extracted from pac.bin before pac.bin can be removed obsolete.
at least getting this extracted i commence further tests and move forward

**Comment by marco-calautti** [comment]
Hi and thanks for your comment. I am not sure I understand well. Are you saying that the EBOOT references a file called boot.lzs, but the extractor does not extract it from the pac.bin?

Are you sure the pac.bin actually contains this file? This might be some development file that was stripped down from the pac.bin in the final release.

**Comment by marco-calautti** [comment]
I have checked the PAC0.BIN, and neither "program" nor "boot.lzs" appear in the list of names in the index.

**Comment by ghost** [comment]
> Hi and thanks for your comment. I am not sure I understand well. Are you saying that the EBOOT references a file called boot.lzs, but the extractor does not extract it from the pac.bin?
> 
> Are you sure the pac.bin actually contains this file? This might be some development file that was stripped down from the pac.bin in the final release.

Hey marco
there were two instances of `boot.lzs` I found, both referenced in a directory:

`program/boot.lzs`

I wasn't sure if this file was in pac.bin because I was quite certain pac.bin was already fully extracted.
I assumed boot.lzs is either as you say, stripped down in the final retail, or (possibly?) archived inside of eboot.bin.

I know some other data related to characters/monster, (item.dat, monster.dat, param.sfo (for save data) etc.) is inside eboot.bin, I wonder if those too are archived files that can be extracted and reimported, since they are also not in pac.bin.

> I have checked the PAC0.BIN, and neither "program" nor "boot.lzs" appear in the list of names in the index.

You're right, I figured pac.bin was fully extracted. I haven't fully cracked loading data from outside just yet, as it still needs pac.bin present to boot, and get the file sizes/offset from.
